#! /bin/sh

case "$1" in
        start)
                echo "Adjusting date"
                start-stop-daemon -S -n setdate.sh -a /usr/bin/setdate.sh -- 20211120 12:23
                ;;

        stop)
                echo "stop date"
                ;;
        *)
                echo "Usage : $0 {start|stop}"
        exit 1
esac